version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quest-capture-server  
    restart: unless-stopped               # Restart policy (always, on-failure, unless-stopped)
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/app/data
