version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - TCP_SERVER_PORT=8080
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - data:/app/data

volumes:
  data:
